### ISSUE TITLE
error on unigornel build: ld: symbol(s) not found for architecture x86_64 (Mac OS X)

### ISSUE THREAD

**Issue by chzyer** [unigornel/unigornel#4]
HI, I'm getting started to unigornel, following [Getting Started](https://www.unigornel.org/doku.php?id=getting_started) to build a unikernel.
Everything is going well until I run 

```
$ unigornel build -o unikernel
```

at the directory `$GOPATH/src/unikernel`

My OS is `OS X 10.11.4`
here is my code from `$GOPATH/src/unikernel/main.go`

``` go
package main

import "C"
import "fmt"

func main() {}

//export Main
func Main(unused int) {
    fmt.Printf("Hello World!\n")
}
```

```
[+] preparing mini-os
make: Nothing to be done for `links'.
[+] compiling Go to a c-archive (/var/folders/gt/1h3746b93sv1__p25q53ktlh0000gn/T/unigornel-carchive692767002)
# runtime/cgo
Undefined symbols for architecture x86_64:
  "_stderr", referenced from:
      _x_cgo_sys_thread_create in gcc_libinit_unigornel.o
      __cgo_sys_thread_start in gcc_unigornel_amd64.o
      _x_cgo_thread_start in gcc_util_unigornel.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[+] removing: /var/folders/gt/1h3746b93sv1__p25q53ktlh0000gn/T/unigornel-carchive692767002.h
[-] warning: remove /var/folders/gt/1h3746b93sv1__p25q53ktlh0000gn/T/unigornel-carchive692767002.h: no such file or directory
error: exit status 2
```

Do you know what is the problem ?
`$GOROOT` and `$UNIGORNEL_MINIOS` are pointed to the correct path.

**Comment by hverr** [comment]
Unfortunately, compiling unikernels with the standard OS X compiler (clang) is impossible as you need to generate ELF files for Xen.

You can either try to install a Linux cross-compiler and set the `CC` environment variable to force Go to use the cross-compiler, or use a standard Linux distribution.

**Comment by chzyer** [comment]
Thanks! It success if I run it in a Linux VM.
